#!/data/data/com.termux/files/usr/bin/env bash
# modificated on 06/21/2020 by Ivam3
#set -euo pipefail
IFS=$'\n\t'
trap ctrl_c 2
ctrl_c(){ printf "$Y\n\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n\n";exit;}
Y='\033[1;33m'
B='\033[1;34m'
R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
W='\033[0m'
apktoolV="2.5.0"
javarepo="https://github.com/ivam3/java/releases/download"
apktool_releases="https://bitbucket.org/iBotPeaches/apktool/downloads"

banner() { printf "$Goke           _   ___     ___  \n          | | / \ \   / / \     \n       _  | |/ _ \ \ / / _ \    \n      | |_| / ___ \ V / ___ \  \n       \___/_/   \_\_/_/   \_\  \n#:For Termux whithout rooted device:#\n#::::::: @Ivan3byCinderella ::::::::#$W\n";}

main() {
	printf "$G(_>)─➤$W usage: bash setup <java8/java9/apktool>\n$G ╰───────➤$W ex1: bash setup java8$G────➤$W To install java8 and dependencies\n$G ╰───────➤$W ex2: bash setup apktool$G───➤$W To change apktool version\n";exit
}

dependencies() {
	command -v npm >/dev/null || yes|apt install perl nodejs
	command -v wget >/dev/null || yes|apt install wget
	command -v git >/dev/null || yes|apt install git
	command -v tar >/dev/null || yes|apt install tar
	command -v aapt >/dev/null || yes|apt install aapt
	command -v proot >/dev/null || yes|apt install proot
}
		
cleanup() { rm -f jdk8_${arch}.tar.gz;rm -rf $PREFIX/share/bin;rm -rf $PWD;rm -rf node-remap-apktool-unicode-filenames;}

get_tar() {
    wget -q --show-progress -c $javarepo/$javaV/jdk8_$arch.tar.gz -O jdk8_$arch.tar.gz
    tar -xf jdk8_$arch.tar.gz -C $PREFIX/share 
    chmod +x $PREFIX/share/bin/*
}

get_binaries() {
cat <<- CONF > $PREFIX/bin/java
#!/usr/bin/bash
unset LD_PRELOAD
export JAVA_HOME="$PREFIX/share/jdk8"
export LIB_DIR="\$PREFIX/share/glib"
export LD_LIBRARY_PATH="\$LIB_DIR"
exec proot -0 \$JAVA_HOME/bin/java "\$@"
CONF
cat <<- CONF > $PREFIX/bin/apktool
#!/usr/bin/bash
export JAVA_HOME="\$PREFIX/share/jdk8"
export LIB_DIR="\$PREFIX/share/glib"
export LD_LIBRARY_PATH=\$LIB_DIR:\$LD_LIBRARY_PATH
umask 000
exec \$PREFIX/bin/java -Xmx1024m -Djava.io.tmpdir=\$JAVA_HOME -jar \$PREFIX/var/spool/apktool.jar -p \$JAVA_HOME "\$@"
CONF
cat <<- CONF > $PREFIX/bin/signapk
#!/usr/bin/bash
unset LD_PRELOAD
export JAVA_HOME="\$PREFIX/share/jdk8"
export LIB_DIR="\$PREFIX/share/glib"
export LD_LIBRARY_PATH="\$LIB_DIR"
umask 000
exec java -Xmx1024m -jar \${JAVA_HOME}/signapk.jar \${JAVA_HOME}/publickey.x509.pem \${JAVA_HOME}/publickey.pk8 "\$@"
CONF
cat <<- CONF > $PREFIX/bin/keytool
#!/usr/bin/bash
unset LD_PRELOAD
export JAVA_HOME="\$PREFIX/share/jdk8"
export LIB_DIR="\$PREFIX/share/glib"
export LD_LIBRARY_PATH="\$LIB_DIR"
exec proot -0 \$JAVA_HOME/bin/keytool "\$@"
CONF
for i in java keytool signapk keytool;do
	chmod +x $PREFIX/bin/$i
done
}

get_apksigner() {
	printf "$G(_>)─➤$W Installing apksigner.\n"
	SOv=$(termux-info|cut -c 1-2|grep "[0-9][0-9]")
	if [[ "$SOv" -gt 7 ]]; then
		apksigner="apksigner"
	else
		apksigner="apksigner-old"
	fi
	command -v apksigner >/dev/null || yes|apt install $apksigner >/dev/null 2>&1
}
get_signapk() {
	printf "$G(_>)─➤$W Installing signapk\n"
	for i in signapk.jar publickey.x509.pem publickey.pk8;do
		mv openjdk/$i $PREFIX/share/jdk8
	done
}
get_keytool() {
	printf "$G(_>)─➤$W Installing keytool\n"
}
get_apktool() {
	printf "$G(_>)─➤$W Installing apktool\n"
	if [ ! -d $PREFIX/var/spool/ ]; then
		mkdir -p $PREFIX/var/spool/
	fi
        wget -q $apktool_releases/apktool_$apktoolV.jar -O $PREFIX/var/spool/apktool.jar
        cp openjdk/lib/libc++_shared.so $PREFIX/share/glib/
}
apktool_fix() {
	printf "$G(_>)─➤$W Remap apktool unicode filenames.\n"
	git clone https://github.com/warren-bank/node-remap-apktool-unicode-filenames >/dev/null 2>&1
	if [ -d node-remap-apktool-unicode-filenames ]; then
		cd node-remap-apktool-unicode-filenames
		npm install --global @warren-bank/node-remap-apktool-unicode-filenames
	else
		printf "$R(_>)─➤$W ERR-rauf\n"
	fi
}
banner
if [[ -z $1 ]]; then
	main
elif [[ $1 = java8 ]]; then
	case "$(dpkg --print-architecture)" in
		aarch64|arm64|armhf|armv8l)
			arch=aarch64
			javaV="1.8.0-152"
			;;
		arm|armv7l|i868)
			arch=arm
			javaV="1.8.0"
			;;
		*)
			printf "$G(_>)─➤$W Architecture not supported\n"
			exit
			;;
	esac
	dependencies
	get_tar
	get_binaries
	get_apksigner
	get_signapk
	get_keytool
	get_apktool
	apktool_fix
	cleanup
elif [[ $1 = java9 ]]; then
	printf "$R(_>)─➤$W Java9 is not available yet\n"
	exit
CXC() {
	for i in dirmngr gnupg-curl;do
		yes|apt install dirmngr >/dev/null 2>&1
	done
	printf "$G(_>)─➤$W Adding PGP key\n"
	apt-key adv --keyserver pool.sks-keyservers.net --recv 9D6D488416B493F0 >/dev/null 2>&1
	printf "$G(_>)─➤$W Adding repository\n"
	mkdir -p $PREFIX/etc/apt/sources.list.d && echo "deb https://termux.xeffyr.ml/ extra main x11" > $PREFIX/etc/apt/sources.list.d/list.list
	printf "$G(_>)─➤$W Updating Termux\n"
	apt update
	printf "$G(_>)─➤$W Installing JAVA 9\n"
	yes|apt install openjdk-9-jdk-headless
}
elif [[ $1 = apktool ]]; then
	apktoolV=$(apktool --version)
	printf "$Y(_>)─➤$W actual apktool version:$Y $apktoolV\n$G(_>)─➤$W Choose a version to install\n"
	for i in 2.5.0 2.4.1 2.4.0 2.3.4 2.3.3 2.3.2 2.3.1 2.3.0 2.2.4 2.2.3 2.2.2 2.2.1 2.2.0 2.1.1 2.1.0 2.0.3 2.0.2 2.0.1 2.0.0;do
		printf "$G ╰───➤$W $i\n"
	done
	while read -p "(_>)─➤ " apktoolV && [ -z $apktoolV ];do continue; done
	if [[ ! -d $PREFIX/var/spool ]]; then
		mkdir $PREFIX/var/spool/apktool.jar
	fi
	wget -q $apktool_releases/apktool_$apktoolV.jar -O $PREFIX/var/spool/apktool.jar
else
	main
fi
printf "$G\n(_>)─➤ DONE!!$W\n"
