#!/data/data/com.termux/files/usr/bin/bash

export LD_PRELOAD=
export LD_LIBRARY_PATH=/data/data/com.termux/files/home/java/openjdk/lib/arm:/data/data/com.termux/files/home/java/openjdk/lib/arm/jli:$LD_LIBRARY_PATH
umask 000
cd $HOME/java/openjdk/

/data/data/com.termux/files/home/java/openjdk/java -Xmx1024m -jar /data/data/com.termux/files/home/java/openjdk/signapk.jar /data/data/com.termux/files/home/java/.embed/publickey.x509.pem /data/data/com.termux/files/home/java/.embed/publickey.pk8 "$@" 

